###

POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "nombre" : "Dylan Gonzalez",
    "Edad" : 17,
    "genero" : "M"
}

###
GET http://localhost:9000/api/users HTTP/1.1
#metodo para mostrar todos los datos existentes en la base de datos

###
GET http://localhost:9000/api/users/6722b8989785ab3c04a1ddd4 HTTP/1.1
#Metodo para mostrar los datos de un id especifico

###
PUT http://localhost:9000/api/users/6722b8989785ab3c04a1ddd4 HTTP/1.1
Content-Type: application/json
#Metodo para actualizar los datos de un id en especifico
{
    "nombre": "Dylan David Gonzalez Rodriguez",
    "Edad": 19,
    "genero": "M"
}

###
DELETE http://localhost:9000/api/users/6722b8989785ab3c04a1ddd4 HTTP/1.1
#Metodo para borrar los datos de un id en especifico